### ISSUE TITLE
Install fails on Win7 / electron

### ISSUE THREAD

**Issue by black-snow** [chesstrian/JSCryptor#10]
I'm tryping to `npm install` jscryptor to my electron app on my Win7 64-bit machine but it fails.

<pre>D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(326): error
C2995: "v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T> &)": Funktionsvorlage wurde ber
eits definiert. [D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\build\mcrypt.vcxpr
oj]
  D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(319): note
  : Siehe Deklaration von "Nan::imp::NanEnsureHandleOrPersistent"
D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(346): error
C2995: "v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T> &)": Funktionsvorlage wurde bereits definier
t. [D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\build\mcrypt.vcxproj]
  D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(334): note
  : Siehe Deklaration von "Nan::imp::NanEnsureLocal"
D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(757): error
C3083: "smalloc": Das Symbol links neben "::" muss ein Typ sein. [D:\_user\Desktop\myapp\app\node_modules
\jscryptor\node_modules\mcrypt\build\mcrypt.vcxproj]
D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(757): error
C2039: "FreeCallback": Ist kein Element von "node" [D:\_user\Desktop\myapp\app\node_modules\jscryptor\nod
e_modules\mcrypt\build\mcrypt.vcxproj]
  C:\Users\user\.node-gyp\4.2.2\include\node\node_object_wrap.h(8): note: Siehe Deklaration von "node"
D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(757): error
C2061: Syntaxfehler: Bezeichner "FreeCallback" [D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_mo
dules\mcrypt\build\mcrypt.vcxproj]
D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(761): error
C2065: "callback": nichtdeklarierter Bezeichner [D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_m
odules\mcrypt\build\mcrypt.vcxproj]
D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(761): error
C2065: "hint": nichtdeklarierter Bezeichner [D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modul
es\mcrypt\build\mcrypt.vcxproj]
D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(768): error
C2665: "node::Buffer::New": Durch keine der 4 Überladungen konnten alle Argumenttypen konvertiert werden. [D:
\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\build\mcrypt.vcxproj]
  C:\Users\user\.node-gyp\4.2.2\include\node\node_buffer.h(43): note: kann "v8::MaybeLocal<v8::Object> node
  ::Buffer::New(v8::Isolate *,char *,size_t)" sein
  C:\Users\user\.node-gyp\4.2.2\include\node\node_buffer.h(31): note: oder "v8::MaybeLocal<v8::Object> node
  ::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)"
  D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(768): note
  : bei Anpassung der Argumentliste "(v8::Isolate *, const char *, uint32_t)"
D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(772): error
C2440: "return": "v8::MaybeLocal<v8::Object>" kann nicht in "v8::Local<v8::Object>" konvertiert werden [D:\_u
ser\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\build\mcrypt.vcxproj]
  D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(772): note
  : Quelltyp konnte von keinem Konstruktor angenommen werden, oder die Überladungsauflösung des Konstruktors
  ist mehrdeutig
D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(779): error
C2039: "Use": Ist kein Element von "node::Buffer" [D:\_user\Desktop\myapp\app\node_modules\jscryptor\node
_modules\mcrypt\build\mcrypt.vcxproj]
  C:\Users\user\.node-gyp\4.2.2\include\node\node_buffer.h(8): note: Siehe Deklaration von "node::Buffer"
D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\node_modules\nan\nan.h(779): error
C3861: "Use": Bezeichner wurde nicht gefunden. [D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_mo
dules\mcrypt\build\mcrypt.vcxproj]
d:\_user\desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt\src\mcrypt.h(10): fatal error C1083
: Datei (Include) kann nicht geöffnet werden: "mcrypt.h": No such file or directory [D:\_user\Desktop\infinis
ee\app\node_modules\jscryptor\node_modules\mcrypt\build\mcrypt.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gy
p\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\n
pm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\
\bin\\npm-cli.js" "install" "jscryptor"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.0.15 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mcrypt@0.0.15 install script 'node-gyp rebuild --release'.
npm ERR! This is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.

> mcrypt@0.0.15 preuninstall D:\_user\Desktop\myapp\app\node_modules\jscryptor\node_modules\mcrypt
> rm -rf build/*

npm ERR! Please include the following file with any support request:
npm ERR!     D:\_user\Desktop\myapp\app\npm-debug.log</pre>

Any guesses?

**Comment by chesstrian** [comment]
JSCryptor depends on mcrypt library which requires libmcrypt, not sure how is the support for windows from mcrypt library, but you could try installing libmcrypt dll file, or compiling it. Another good idea is to ask directly to mcrypt developer about windows support or steps to install in on windows platforms. Hope this gets you some hints.

**Comment by rezigned** [comment]
@chesstrian I've experienced the same problem and found out that mcrypt v0.0.15 doesn't work with latest nodejs (>= 4) so i've opened pull request here (that fixed this problem).
https://github.com/chesstrian/JSCryptor/pulls

**Comment by black-snow** [comment]
@chesstrian thanks for the reply. I'm quite new to node and npm - when will the newest version be available via npm so I can give it another shot?

**Comment by chesstrian** [comment]
Sorry @black-snow, it's published now.
