### ISSUE TITLE
Problem with binary data

### ISSUE THREAD

**Issue by enricodeleo** [chesstrian/JSCryptor#12]
Hi!
I'm trying to make this module work with other RNCryptor's flavours (java, php and obj-c), but when I try to decrypt a file with binary contents (originally encrypted with the PHP version) the result is malformed.

I'm doing something like this:

```
[...]
var password = 'mypass';
var b64string = fs.readFileSync('/path/to/file.enc', 'utf-8');
var decrypted = RNCryptor.Decrypt(b64string, password);
touch('/path/to/file.jpg', function() {
  fs.writeFileSync('/path/to/file.jpg', decrypted); 
});
```

Doing the same job with the java or obj-c version produces no problems.

Any idea?

**Comment by chesstrian** [comment]
Thanks for reporting this, will give it a check.

**Comment by chesstrian** [comment]
@enricodeleo You save the encrypted string which is in base64 to `file.enc`, when you read this file, you don't read a base64 string but an utf-8 string, you need to make the conversion before decrypting, so:

```js
var b64string = new Buffer(fs.readFileSync('/path/to/file.enc').toString(), 'base64');
```
Note that replacing `'utf-8'` for `'base64'` doesn't do the job, also `fs.readFileSync` returns a Buffer, then you need to convert it again to string using `toString` method.

Please let me know if this works.

**Comment by enricodeleo** [comment]
@chesstrian thank you for your reply! I tried as you suggested but the problem seems to be the same.
Also, opening the final file with vim, I get something like (reporting the first lines):
```
���^@^PJFIF^@^A^A^A^A,^A,^@^@��^LXICC_PROFILE^@^A^A^@^@^LHLino^B^P^@^@mntrRGB XYZ ^G�^@^B^@    ^@^F^@1^@^@acspMSFT^@^@^@^@IEC sRGB^@^@^@^@^@^@^@^@^@^@^@^@^@^@��^@^A^@^@^@^@�-HP  ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^Qcprt^@^@^AP^@^@^@3desc^@^@^A�^@^@^@lwtpt^@^@^A�^@^@^@^Tbkpt^@^@^B^D^@^@^@^TrXYZ^@^@^B^X^@^@^@^TgXYZ^@^@^B,^@^@^@^TbXYZ^@^@^B@^@^@^@^Tdmnd^@^@^BT^@^@^@pdmdd^@^@^B�^@^@^@�vued^@^@^CL^@^@^@�view^@^@^C�^@^@^@$lumi^@^@^C�^@^@^@^Tmeas^@^@^D^L^@^@^@$tech^@^@^D0^@^@^@^LrTRC^@^@^D<^@^@^H^LgTRC^@^@^D<^@^@^H^LbTRC^@^@^D<^@^@^H^Ltext^@^@^@^@Copyright (c) 1998 Hewlett-Packard Company^@^@desc^@^@^@^@^@^@^@^RsRGB IEC61966-2.1^@^@^@^@^@^@^@^@^@^@^@^RsRGB IEC61966-2.1^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```

This appear like a binary jpg file, so the module actually decrypts data (both with or without the `new Buffer` meethod you suggested above) but may be it loose some some part. What do you think about it?

**Comment by chesstrian** [comment]
@enricodeleo Please provide me your file.enc encrypted with `'mypass'` password, want to try to decrypt it, Maybe I found a different issue.

**Comment by chesstrian** [comment]
The issue was that decrypted data had some bits less.
