### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by jimmytaker** [chesstrian/JSCryptor#14]
This is more a story and a problem + solution than it is a bug report, as no real bug is present here.
I have been getting into node js for the past few days, and I encountered an issue that some of you out there might think "duh...", but I still wasted a full day on it. To the issue:
I am a Qt developer first and foremost. JavaScript is a side interest.
I develop with VS 2012 Pro. It is good for writing JavaScript, so I began Node JS stuff in it as well. If you are going my way - STOP it. Node JS V8 Engine is C+11. MSVC 2012 is not. You will run into countless issues doing "npm install x" and the reason will be your compiler.
JSCrypter does not install with VS2012 (and neither with VS2013) due to mcrypt. However, it does install from the VS2015 x64 Command Prompt without a hiccup.
So if there is an issue that JSCryptor needs to handle - it is only to write as a requirement for install on Windows: VS2015 (Community Edition works fine).
Happy coding!

**Comment by black-snow** [comment]
This is true for many npm packages, VS2015+ should always be present.

**Comment by chesstrian** [comment]
Hi guys, to be honest I'm not a big Microsoft fun, so, I have no way to check this, any help here is welcome.

**Comment by black-snow** [comment]
As far as I can see there's nothing to do here. You add a section the the README saying that VS2015 (express or any other) is (most probably) required on windows machines.

**Comment by chesstrian** [comment]
Thanks guys.

**Comment by black-snow** [comment]
@chesstrian You're welcome. Also good job here, jscryptor is running quite fine. Will see how the performance goes in real-life scenarios :)
