### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by domino3d** [chesstrian/JSCryptor#15]
Hi
i used jscryptor for decoding text (with special characteres) encrypted in RNcryptor on iOS - this is working fine.
But i tried to encode text with jscryptor with some special characters in text and store it ( I believe they are utf8 characters) and i got problem. The problem is it encode special character badly.
Without special characters it is working fine.

Where do i setup character encoding? Is it possible?
After loading and decoding stored data, it looks like 1st part on attached pic:
The second part is encoded in RNcryptor on iOS

![snimek obrazovky 2016-04-12 v 19 58 37](https://cloud.githubusercontent.com/assets/10728013/14599853/159f7e80-055a-11e6-8c1f-fa58c358beb4.png)

Decrypt code in js looks like this:

> ```
>   var password = res.app.get('crypto_pass').password;
>   var enc = RNCryptor.Encrypt(data, password);
>   return enc.toString(); 
> ```

**Comment by domino3d** [comment]
ok, so the solution was to add node buffer

> 		data = new Buffer(data);
> 		var enc = RNCryptor.Encrypt(data, password);

**Comment by chesstrian** [comment]
It's strange it happens because the library does exactly that, will give a check.

**Comment by chesstrian** [comment]
Yes, the data is converted to buffer for the library but taking it as binary, better to pass the Buffer directly.
