### ISSUE TITLE
Module name "crypto" has not been loaded yet for context

### ISSUE THREAD

**Issue by pareta2** [chesstrian/JSCryptor#19]
I am getting this error

Module name "crypto" has not been loaded yet for context

Could you please tell me where can i find crypto module file to include??

**Comment by chessudo** [comment]
Hi @pareta2, sorry for the delay, Have you installed the lib-mcrypt dependency library?, What is your OS?.

**Comment by chesstrian** [comment]
Hi @pareta2, sorry for the delay, was due to vacations.

Have you installed the lib-mcrypt dependency library?, What is your OS?.

**Comment by pareta2** [comment]
I was trying to implement in a hybrid application like phonegap where Cordova plugins works or java script works but no luck

**Comment by chesstrian** [comment]
This library is for server side, there is a work in progress for client side, though abandoned, here: https://github.com/RNCryptor/rncryptor-js.

Can I recommend the native library? See the group: https://github.com/RNCryptor
