### ISSUE TITLE
Problem import RNCryptor

### ISSUE THREAD

**Issue by mlfaa** [chesstrian/JSCryptor#22]
I have problem when import RNCryptor:

This error in console: "Cannot read property 'indexOf' of undefined" 

I import two differents forms: 

```
var RNCryptor = require('jscryptor');
```

```
import RNCryptor = require(from 'jscryptor';
```
 Both presents error. Can someone help me?

**Comment by arpitvaishnav** [comment]
I am facing exactly the same issue as @mlfaa is facing. Is there any support available nowadays?

**Comment by chesstrian** [comment]
New version published, provide larger code and tracebacks for issues like this in the future please.
