### ISSUE TITLE
Can't compile on heroku because of mcrypt

### ISSUE THREAD

**Issue by thinkv** [chesstrian/JSCryptor#6]
Hey guys, i know this snippet is mcrypt .13 but its the same with .7, im just wondering if there is anyway to use a precompiled, or another version?

Hi guys, trying to compile on heroku, seem to keep getting this?

any ideas?

thanks!
-----> Building Meteor App Bundle
npm-container: updating npm dependencies -- jscryptor, mcrypt...
npm WARN package.json packages-for-meteor-smartpackage-1dwsjqb@0.0.0 No
description
npm WARN package.json packages-for-meteor-smartpackage-1dwsjqb@0.0.0 No
repository field.
npm WARN package.json packages-for-meteor-smartpackage-1dwsjqb@0.0.0 No README
data
In file included from ../src/mcrypt.cc:3:0:
../src/mcrypt.h:10:20: fatal error: mcrypt.h: No such file or directory
#include 
^
compilation terminated.
make: *** [Release/obj.target/mcrypt/src/mcrypt.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit

**Comment by chesstrian** [comment]
Hi @thinkv, looks like the problem is the dependencies in the SO, in Ubuntu you need:
```sh
sudo apt-get install libmcrypt4 libmcrypt-dev
```

**Comment by thinkv** [comment]
but how can I do this on Heroku?

**Comment by chesstrian** [comment]
I didn't work on Heroku before, but searching in Google I can see this:
```sh
heroku run bash
```
after that you are in the shell of the heroku system, try to run the previous command after it.

**Comment by thinkv** [comment]
So i found a build package that installs from apt (only way), however heroku-buildpack-apt installs things in a newly created folder /app/.apt/ . How can I make this compile if that's where it's being installed?

Someone had the same problem with python, and they had to set PYTHONPATH=/app/.apt/usr/lib/python2.7/dist-packages/

Thanks mate!

**Comment by chesstrian** [comment]
I think is a good idea to give a try to this: http://stackoverflow.com/questions/558803/how-to-add-a-default-include-path-for-gcc-in-linux

**Comment by chesstrian** [comment]
@thinkv Latest mcrypt working version is 0.0.7, otherwise you get `TypeError: Invalid iv size. You can determine iv size using getIvSize()` while encrypting. This is already reported on issue #5, if you want to work with the latest mcrypt version, feel free to fix this and share :smile:

**Comment by thinkv** [comment]
Hey @chesstrian I know this :) problem is, i can't get any version of mcrypt to compile on there. I had a look at that link but I have no idea what i am doing, how can I actually find the path the libs are located in?

**Comment by thinkv** [comment]
so i managed to compile the mcrypt binaries in a directory on the system, but i do not know how to make the mcrypt use them when compiling, any ideas?

**Comment by chesstrian** [comment]
This library is useless without `mcrypt`.
